#Se especifica que se va a utilizar la version 2.1 de docker compose file
#Referencia a https://docs.docker.com/compose/compose-file/compose-file-v2/
version: '2.1'

#Se indica que se crean servicios
services:
#Se nombra a los servicios
#b1, b2 y b3 son routers de borde de SA. 
  b2:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10201:2601
      #ospf ipv6
      - 10203:2606
      #bgp
      - 10204:2605
    networks:
      b1_b2:
        ipv6_address: 2001:c:c:c::b
      b2_r4:
        ipv6_address: 2001:bbbb:bbbb:24::2
      b2_r6:
        ipv6_address: 2001:bbbb:bbbb:26::2
      b2_r8:
        ipv6_address: 2001:bbbb:bbbb:28::2
 
  
  
  r4:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10411:2601
      #ospf ipv6
      - 10413:2606
    networks:
      b2_r4:
        ipv6_address: 2001:bbbb:bbbb:24::4

  r6:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10611:2601
      #ospf ipv6
      - 10613:2606
    networks:
      b2_r6:
        ipv6_address: 2001:bbbb:bbbb:26::6
      r6_r8:
        ipv6_address: 2001:bbbb:bbbb:68::6
      r6_h12:
        ipv6_address: 2001:bbbb:bbbb:612::6

 
  r8:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 10811:2601
      #ospf ipv6
      - 10813:2606
    networks:
      b2_r8:
        ipv6_address: 2001:bbbb:bbbb:28::8
      r6_r8:
        ipv6_address: 2001:bbbb:bbbb:68::8
      r8_h14:
        ipv6_address: 2001:bbbb:bbbb:814::8

 

  ##Se aplican los mismos comentarios sobre h12
  h12:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/h12/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/h12/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 11211:2601
      #ospf ipv6
      - 11213:2606
    networks:
          r6_h12:
            ipv6_address: 2001:bbbb:bbbb:612::12

  ##Se aplican los mismos comentarios sobre h14
  h14:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/h14/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/h14/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      - 11411:2601
      #ospf ipv6
      - 11413:2606
    networks:
          r8_h14:
            ipv6_address: 2001:bbbb:bbbb:814::14


#Se definen los enlaces y las redes a las cuales pertenecen
networks:
  b1_b2:
    #Se usa bridge como driver para poder conectar los dockers en el host.
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:c:c:c:c::/64
 
  
  b2_r4:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:24::/64

  b2_r6:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:26::/64

  b2_r8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:28::/64


  r6_r8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:68::/64

  r6_h12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:612::/64

 
  r8_h14:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:814::/64
