#!/bin/bash

echo "#### BORRAR IPv4 default gateway ###"
sudo docker exec bgp_h11_1 ip route del default
sudo docker exec bgp_h12_1 ip route del default
sudo docker exec bgp_h13_1 ip route del default
sudo docker exec bgp_h14_1 ip route del default
sudo docker exec bgp_r3_1 ip route del default
sudo docker exec bgp_r4_1 ip route del default
sudo docker exec bgp_r5_1 ip route del default
sudo docker exec bgp_r6_1 ip route del default
sudo docker exec bgp_r7_1 ip route del default
sudo docker exec bgp_r8_1 ip route del default
sudo docker exec bgp_r9_1 ip route del default
sudo docker exec bgp_b1_1 ip route del default
sudo docker exec bgp_b2_1 ip route del default
sudo docker exec bgp_b3_1 ip route del default

echo "### BORRAR IPv6 DEFAULT GATEWAY###" 
sudo docker exec bgp_r3_1 ip -6 route del default
sudo docker exec bgp_r4_1 ip -6 route del default
sudo docker exec bgp_r5_1 ip -6 route del default
sudo docker exec bgp_r6_1 ip -6 route del default
sudo docker exec bgp_r7_1 ip -6 route del default
sudo docker exec bgp_r8_1 ip -6 route del default
sudo docker exec bgp_r9_1 ip -6 route del default
sudo docker exec bgp_b1_1 ip -6 route del default
sudo docker exec bgp_b2_1 ip -6 route del default
sudo docker exec bgp_b3_1 ip -6 route del default
sudo docker exec bgp_h11_1 ip -6 route del default
sudo docker exec bgp_h12_1 ip -6 route del default
sudo docker exec bgp_h13_1 ip -6 route del default
sudo docker exec bgp_h14_1 ip -6 route del default
sudo docker exec bgp_h11_1 ip -6 route add default via 2001:aaaa:aaaa:6::5
sudo docker exec bgp_h12_1 ip -6 route add default via 2001:bbbb:bbbb:6::6
sudo docker exec bgp_h13_1 ip -6 route add default via 2001:aaaa:aaaa:7::7
sudo docker exec bgp_h14_1 ip -6 route add default via 2001:bbbb:bbbb:7::8

echo "### AGREGANDO GATEWAY ESTATICO ###"
sudo docker exec bgp_r3_1 ip -6 route add default via 2001:aaaa:aaaa:1::111
sudo docker exec bgp_r4_1 ip -6 route add default via 2001:bbbb:bbbb:1::111
sudo docker exec bgp_r5_1 ip -6 route add default via 2001:aaaa:aaaa:2::111
sudo docker exec bgp_r6_1 ip -6 route add default via 2001:bbbb:bbbb:2::111
sudo docker exec bgp_r7_1 ip -6 route add default via 2001:aaaa:aaaa:3::111
sudo docker exec bgp_r8_1 ip -6 route add default via 2001:bbbb:bbbb:3::111
sudo docker exec bgp_r9_1 ip -6 route add default via 2001:cccc:cccc:1::3