version: '2.1'

services:
#-------------------------------------------
#     ####  ROUTER DE BORDE (BGP)  ####
#-------------------------------------------

  b2:
    build: ./bgp/.
    volumes:
      - ./volumes/bgp/b2/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/bgp/b2/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/bgp/b2/bgpd.conf:/etc/quagga/bgpd.conf:ro
      - ./volumes/bgp/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: bgp:20180426
    privileged: true
    ports:
      #admin
      - 10101:2601
      #ospf ipv6
      - 10103:2606
      #bgp
      - 10104:2605
    networks:
      nb1b2:
        ipv6_address: 2001:c:c:c::9
      nr4b2:
        ipv6_address: 2001:bbbb:bbbb:1::111
      nr6b2:
        ipv6_address: 2001:bbbb:bbbb:2::111
      nr8b2:
        ipv6_address: 2001:bbbb:bbbb:3::111
      proxynet:
          ipv6_address: 2001:bbbb:bbbb:10::111        

#----------------------------------------
#     ####    SERVIDOR DNS    ####
#----------------------------------------

  bind2:
    restart: always
    image: sameersbn/bind:latest
    volumes:
      - ./srv/docker/bind:/data
    privileged: true
    dns: 127.0.0.1
    environment:
      - 'ROOT_PASSWORD=ubuntu'
    ports:
      - 10000:10000/tcp
      # - 53:53/udp    
    networks:
      nr4dns:
        ipv6_address: 2001:bbbb:bbbb:8::4

#----------------------------------------
#     ####    ROUTERS INTERNOS    ####
#----------------------------------------

  r4:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r4/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r4/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      #- 10311:2601
      #ospf ipv6
      - 10313:2606
    networks:
      nr4b2:
        ipv6_address: 2001:bbbb:bbbb:1::3
      nr4dns:
        ipv6_address: 2001:bbbb:bbbb:8::3
      nr3ng:
        ipv6_address: 2001:bbbb:bbbb:9::3

  r6:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r6/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r6/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      #- 10511:2601
      #ospf ipv6
      - 10513:2606
    networks:
      nr6b2:
        ipv6_address: 2001:bbbb:bbbb:2::5
      nr6nr8:
        ipv6_address: 2001:bbbb:bbbb:5::5
      nr6h12:
        ipv6_address: 2001:bbbb:bbbb:6::5  

  r8:
    build: ./ospf/.
    volumes:
      - ./volumes/ospf/r8/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/r8/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
    image: ospf:20180419
    privileged: true
    ports:
      #admin
      #- 10711:2601
      #ospf ipv6
      - 10713:2606
    networks:
      nr8b2:
        ipv6_address: 2001:bbbb:bbbb:3::7
      nr6nr8:
        ipv6_address: 2001:bbbb:bbbb:5::7
      nr8h14:
        ipv6_address: 2001:bbbb:bbbb:7::7

#--------------------------------
#     ####    HOSTS    ####
#--------------------------------

  h12:
    #build: ./host/.
    volumes:
      - ./volumes/ospf/h12/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/h12/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./ssl/CA/TP7-redes.crt:/usr/share/ca-certificates/extra/TP7-redes.crt
    image: ospf:20180419
    privileged: true
    networks:
      nr6h12:
        ipv6_address: 2001:bbbb:bbbb:6::11

  h14:

    #build: ./host/.
    volumes:
      - ./volumes/ospf/h14/zebra.conf:/etc/quagga/zebra.conf:ro
      - ./volumes/ospf/h14/ospf6d.conf:/etc/quagga/ospf6d.conf:ro
      - ./volumes/ospf/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf:ro
      - ./ssl/CA/TP7-redes.crt:/usr/share/ca-certificates/extra/TP7-redes.crt
    image: ospf:20180419
    privileged: true
    networks:
      nr8h14:
        ipv6_address: 2001:bbbb:bbbb:7::13


#========================================
#############  WEB SERVER ###############
#======================================== 


  rp:
      image: nginx:alpine
      privileged: true
      volumes:
        - ./ssl:/ssl
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      restart: always
      networks:
        strapinet:
          ipv6_address: 2001:d:d:d::4 
        mongonet:
          ipv6_address: 2001:e:e:e::4
        nr3ng:
          ipv6_address: 2001:bbbb:bbbb:9::4


  api:
    build: ./strapi/.
    image: strapi/strapi
    volumes: 
      - ./strapi-app:/usr/src/api/strapi-app
    privileged: true
    dns: 
      - 8.8.8.8
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=[2001:d:d:d::4]
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - HOST=localhost
    depends_on:
      - db1
      - rp
    #restart: always
    networks:
      strapinet:
        ipv6_address: 2001:d:d:d::3

  db1:
    image: mongo
    privileged: true
    environment:
      - MONGO_INITDB_DATABASE=strapi
    depends_on:
      - rp
    volumes:
      - ./db1:/data/db
    #restart: always
    command: mongod --ipv6 --bind_ip_all 
    networks:
      mongonet:
        ipv6_address: 2001:e:e:e::5
        
#=================================================
#     ##########   PROXY SQUID   ###########
#=================================================

  squid:
      image: sameersbn/squid:3.3.8-23
      volumes:
        - ./squid:/var/spool/squid3
      restart: always
      networks:
        proxynet:
          ipv6_address: 2001:bbbb:bbbb:10::3

#=================================================
#    ##########   NETWORKS   ###########
#=================================================


networks:

  strapinet:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
         - subnet: 2001:d:d:d::/64

  mongonet:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
         - subnet: 2001:e:e:e::/64


  nb1b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:c:c:c::/64
          gateway: 2001:c:c:c::3

# RED 1
  nr4b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:1::/64

  nr6b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:2::/64

  nr8b2:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:3::/64

  nr6nr8:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:5::/64

  nr6h12:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:6::/64

  nr8h14:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:7::/64

  nr4dns:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 2001:bbbb:bbbb:8::/64

  nr3ng:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
         - subnet: 2001:bbbb:bbbb:9::/64

  proxynet:
    driver: "bridge"
    enable_ipv6: true
    ipam:
      driver: default
      config:
         - subnet: 2001:bbbb:bbbb:10::/64
